sudo: required
language: python

services:
  - docker
python:
  - "2.7"

before_install:
#  - docker build -t bairdo/faucet-tests -f Dockerfile.tests .
#  - docker run --privileged -ti bairdo/faucet-tests
#  - docker ps -a
  - docker build -t bairdo/faucet-tests-auth -f Dockerfile.auth .
  - "sudo apt-get install graphviz"
  - "sudo pip install -r requirements.txt"

install:
  - "make"
script:
  - "cd ./tests ; ./test_config.py ; ./test_check_config.py ; ./test_valve.py"
  - docker run --privileged -ti bairdo/faucet-tests-auth | tee /dev/tty |awk '/FAILED \(fail/{f=1} END{exit f}'
#  - docker ps -a

