language: python
python:
  - "2.7"
sudo: required
before_install:
  - "sudo apt-get install graphviz"
  - "sudo pip install -r requirements.txt"
install:
  - "make"
#  - "mkdir -p /etc/ryu/faucet"
#  - "touch /etc/ryu/faucet/faucet_mac_learning.txt"
script:
  - "cd ./tests ; ./test_config.py ; ./test_check_config.py ; ./test_valve.py"
